import type { WorkbenchSnapshot } from "@agenthub/contracts";

const now = "2026-05-21T00:00:00.000Z";

export function snapshot(
  status: "online" | "offline" | "degraded" | "active-running" = "online",
): WorkbenchSnapshot {
  return {
    activeConversationId: "conversation_1",
    activeWorkspaceId: "workspace_1",
    agents: [
      {
        capabilityTags: ["planning"],
        createdAt: now,
        displayName: "Orchestrator",
        id: "agent_1",
        ownerUserId: "user_1",
        policy: {},
        providerId: "provider_1",
        role: "orchestrator",
        systemPrompt: "Plan work",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
      {
        capabilityTags: ["code", "review"],
        createdAt: now,
        displayName: "Implementer",
        id: "agent_2",
        ownerUserId: "user_1",
        policy: {},
        providerId: "provider_1",
        role: "worker",
        systemPrompt: "Implement work",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
      {
        capabilityTags: ["research"],
        createdAt: now,
        displayName: "Researcher",
        id: "agent_researcher",
        ownerUserId: "user_1",
        policy: { network: "ask" },
        providerId: "provider_1",
        role: "worker",
        systemPrompt: "Research before coding.",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
    ],
    authenticated: true,
    availableActions: ["run.create"],
    conversations: [
      {
        archivedAt: null,
        createdAt: now,
        id: "conversation_1",
        kind: "group",
        notificationsMuted: false,
        ownerUserId: "user_1",
        pinnedAt: null,
        projectId: "project_1",
        title: "MVP workbench",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
    ],
    messages: [
      {
        authorId: "agent_2",
        authorKind: "agent",
        conversationId: "conversation_1",
        createdAt: now,
        id: "message_1",
        ownerUserId: "user_1",
        parts: [
          { text: "Implemented **the shell**\n\n## Details\n- `pnpm check`", type: "markdown" },
        ],
        replyToMessageId: null,
        updatedAt: now,
      },
    ],
    runtimeDevices: [
      {
        appVersion: "0.1.0",
        capabilities: ["git-diff", "permissions", "smoke-provider"],
        createdAt: now,
        displayName: "Local Runtime",
        id: "runtime_1",
        lastHeartbeatAt: now,
        ownerUserId: "user_1",
        platform: "macos",
        status,
        updatedAt: now,
      },
    ],
    providerHealth: {
      providerMode: "claude-code",
      status: "connected",
      binaryPathLabel: "/usr/local/bin/claude",
      checkedAt: now,
      failureReason: null,
    },
    memoryHealth: {
      enabled: true,
      status: "connected",
      url: "http://127.0.0.1:3111",
      viewerUrl: "http://127.0.0.1:3113",
      checkedAt: now,
      failureReason: null,
    },
    runs: [
      {
        agentId: "agent_2",
        completedAt: null,
        conversationId: "conversation_1",
        createdAt: now,
        failureReason: null,
        id: "run_1",
        ownerUserId: "user_1",
        planId: "plan_1",
        projectId: "project_1",
        startedAt: now,
        status: "running",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
    ],
    userId: "user_1",
    projects: [
      {
        archivedAt: null,
        createdAt: now,
        dirty: false,
        gitBaseCommit: "abc123",
        gitBranch: "main",
        id: "project_1",
        isDefault: false,
        lastUsedAt: now,
        localPath: "/Users/chihayaanon/IdeaProjects/agenthub",
        localPathLabel: "~/IdeaProjects/agenthub",
        name: "AgentHub",
        ownerUserId: "user_1",
        repoUrl: null,
        runtimeDeviceId: "runtime_1",
        updatedAt: now,
        workspaceId: "workspace_1",
      },
    ],
    workspaceMetadata: {
      dirty: false,
      displayName: "AgentHub",
      gitBaseCommit: "abc123",
      gitBranch: "main",
      localPathLabel: "~/IdeaProjects/agenthub",
      providerCapabilities: ["smoke"],
      workspaceId: "workspace_1",
    },
    workspaces: [
      {
        createdAt: now,
        defaultBranch: "main",
        id: "workspace_1",
        localPath: "/Users/chihayaanon/IdeaProjects/agenthub",
        name: "AgentHub",
        ownerUserId: "user_1",
        repoUrl: null,
        runtimeDeviceId: "runtime_1",
        runtimeKind: "local",
        updatedAt: now,
      },
    ],
  };
}
